import { HousingListing, RoommateProfile } from './types';

export const initialListings: HousingListing[] = [
  {
    id: 'al-noor-a',
    title: 'Al-Noor Cottage A',
    university: 'Mindanao State University Main Campus',
    distance: '3 min walk to Main Gate',
    price: 800,
    type: 'Bed Space',
    wifi: true,
    insideCR: true,
    withSink: true,
    cctv: true,
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    landlordName: 'Haji Ahmad Ali',
    description: 'Affordable, secure, and clean dormitory environment specifically designed for MSU students. Located just right outside the campus gate with a quiet study atmosphere, high-speed internet, and regular maintenance.',
    amenities: ['Free Wi-Fi', 'Inside CR', 'With Sink', 'CCTV', 'Study Desk & Chair', 'Individual Storage Lockers', 'Filtered Drinking Water'],
    rules: ['10 PM Curfew', 'No Smoking Indoors', 'Visitors permitted in lounge only', 'Quiet hours: 9 PM - 6 AM']
  },
  {
    id: 'al-noor-b',
    title: 'Al-Noor Cottage B',
    university: 'Mindanao State University Main Campus',
    distance: '3 min walk to Main Gate',
    price: 1200,
    type: 'Shared Room',
    wifi: true,
    insideCR: true,
    withSink: true,
    cctv: true,
    image: 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    landlordName: 'Haji Ahmad Ali',
    description: 'Shared room option in Al-Noor Cottage with extra spacious floor plan and private cabinet space. Features newly installed exhaust fans and excellent ventilation.',
    amenities: ['Free Wi-Fi', 'Inside CR', 'With Sink', 'CCTV', 'Individual Wardrobes', 'Shared Kitchen Privileges'],
    rules: ['10 PM Curfew', 'No Cooking of heavy meals inside rooms', 'Visitors allowed until 7 PM']
  },
  {
    id: 'marawi-heights',
    title: 'Marawi Heights Dormitory',
    university: 'Mindanao State University Main Campus',
    distance: '5 min walk to MSU',
    price: 1800,
    type: 'Single Room',
    wifi: true,
    insideCR: true,
    withSink: true,
    cctv: true,
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    landlordName: 'Mrs. Fatima Solaiman',
    description: 'Premium single rooms for students seeking privacy and a focused academic environment. Each room has a dedicated window view overlooking the campus landscape.',
    amenities: ['High-speed Wi-Fi', 'Private CR', 'With Sink', '24/7 CCTV', 'Study Table', 'Exhaust Fan', 'Laundry Area access'],
    rules: ['No Curfew', 'No Pets', 'No Overnight Guests without prior notice']
  },
  {
    id: 'darussalam-hall',
    title: 'Darussalam Ladies Hall',
    university: 'Mindanao State University Main Campus',
    distance: '4 min walk to Main Gate',
    price: 1500,
    type: 'Bed Space',
    wifi: true,
    insideCR: true,
    withSink: true,
    cctv: true,
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    landlordName: 'Amina Macarambon',
    description: 'All-female premium lodging house prioritizing safety, neatness, and student welfare. Highly accessible and fully guarded 24/7.',
    amenities: ['Free Wi-Fi', 'Inside CR', 'With Sink', 'CCTV', 'Common Study Lounge', 'GCash/Bank transfer rent options'],
    rules: ['9:30 PM Curfew (Strict)', 'Female visitors only in reception', 'Cleanliness duty rotation']
  },
  {
    id: 'up-camp-studio',
    title: 'Academic Studio Oasis',
    university: 'UP Diliman Campus',
    distance: '8 min walk to Academic Oval',
    price: 4500,
    type: 'Studio',
    wifi: true,
    insideCR: true,
    withSink: true,
    cctv: true,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    landlordName: 'Professor Reyes',
    description: 'Fully furnished studio unit ideal for graduate students or faculty members. Highly quiet and situated in a safe residential enclave with rich greenery.',
    amenities: ['100 Mbps Wi-Fi', 'Private Kitchen & CR', 'Air Conditioning', 'CCTV Guarded Street', 'Work Desk'],
    rules: ['No Loud Parties', 'No Smoking', 'Garbage separation rules apply']
  },
  {
    id: 'ust-suite',
    title: 'Thomasian Bed Space Hub',
    university: 'University of Santo Tomas',
    distance: '2 min walk to España Boulevard',
    price: 2000,
    type: 'Bed Space',
    wifi: true,
    insideCR: true,
    withSink: false,
    cctv: true,
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1000',
    isVerified: true,
    landlordName: 'Mr. Ken Dy',
    description: 'Convenient student dorm in the heart of Manila. Walking distance to UST gate, review centers, and restaurants. Perfect for medical or engineering students.',
    amenities: ['Free Wi-Fi', 'Airconditioned room', 'CCTV Security', 'Elevator access', 'Common Study Area'],
    rules: ['11 PM Curfew', 'Biometric log-in', 'No drinking or gambling']
  }
];

export const initialRoommates: RoommateProfile[] = [
  {
    id: 'roomie-renalyn',
    name: 'Renalyn Joyce Bascones',
    age: 20,
    gender: 'Female',
    course: 'BS Computer Science',
    year: 3,
    tags: ['Early Bird', 'Hate Alarm Clock', 'Code Night Owl', 'Clean Freak'],
    sleepSchedule: 'Sleeps at 1 AM, Wakes at 7 AM',
    cleanliness: 'Extremely clean & organized',
    budget: '₱800 - ₱1500',
    bio: 'Looking for a quiet, study-oriented roommate in Marawi. I spend most of my time coding or reading, and I appreciate a neat shared space. Let’s co-work and conquer CS!'
  },
  {
    id: 'roomie-ahmad',
    name: 'Ahmad Macarambon',
    age: 19,
    gender: 'Male',
    course: 'BS Civil Engineering',
    year: 2,
    tags: ['Heavy Sleeper', 'Silent Co-liver', 'Gym Enthusiast', 'No Smoking'],
    sleepSchedule: 'Sleeps at 11 PM, Wakes at 6 AM',
    cleanliness: 'Moderate',
    budget: '₱1000 - ₱2000',
    bio: 'Civil Engineering sophomore here! I stay out studying at the library most of the time. Respectful of privacy, non-smoker, and looking to share an Al-Noor unit.'
  },
  {
    id: 'roomie-norhazima',
    name: 'Norhazima Lucman',
    age: 21,
    gender: 'Female',
    course: 'BS Nursing',
    year: 4,
    tags: ['Study Groupie', 'Strict Curfew Helper', 'Nature Lover', 'Tea Drinker'],
    sleepSchedule: 'Sleeps at 10:30 PM, Wakes at 5:30 AM',
    cleanliness: 'Very tidy',
    budget: '₱1200 - ₱2500',
    bio: 'Nursing clinical student looking for a female roommate. Very busy schedule with shifts, so looking for a peaceful sleep-friendly room without loud music or distractions.'
  },
  {
    id: 'roomie-jeric',
    name: 'Jeric Santos',
    age: 18,
    gender: 'Male',
    course: 'BS Accountancy',
    year: 1,
    tags: ['Quiet study', 'Early Riser', 'Thrifty Cook', 'Friendly'],
    sleepSchedule: 'Sleeps at 10 PM, Wakes at 6 AM',
    cleanliness: 'High',
    budget: '₱800 - ₱1200',
    bio: 'Freshman Accountancy student adjusting to college life. I like to cook simple food to save money, keep things highly organized, and prefer a roommate who values early sleep.'
  }
];
